version: '3'

services:
  web:
    build: .
    command: python CC_130_185_252_279_code.py
    restart: always
    ports:
      - "5000:5000"
    links:
      - sqlite3
    depends_on:
      - sqlite3
  sqlite3:
    image: nouchka/sqlite3:latest
    ports: 
      - "27017:27017"
