version: '3'

services:
  web:
    build: .
    container_name: users
    image: users:latest
    command: python3 user.py
    restart: always
    ports:
      - "80:80"
    environment:
      - TEAM_NAME=CC_130_185_252_279
    links:
      - sqlite3
    depends_on:
      - sqlite3
  sqlite3:
    image: nouchka/sqlite3:latest
    ports: 
      - "27017:27017"
