version: '3'

services:
  web:
    build: .
    command: python user.py
    restart: always
    ports:
      - "8080:8080"
    links:
      - sqlite3
    depends_on:
      - sqlite3
  sqlite3:
    image: nouchka/sqlite3:latest
    ports: 
      - "27017:27017"
