version: '3.1'

services:
  zoo:
    image: zookeeper
    restart: on-failure
    hostname: zoo
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  rmq:
    image: rabbitmq:3.8.3-alpine

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    image: zookeperamqp_producer:latest
    command: sh -c "sleep 50 && python slave.py"
    restart: on-failure
    links:
    - rmq
    - zoo
    depends_on:
    - rmq
    - zoo
  consumer:
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "sleep 50 && python master.py"
    restart: on-failure

    links:
    - rmq
    - zoo
    depends_on:
    - rmq
    - zoo
  
  orchestrator:
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "sleep 60 && python orch.py"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    links:
    - rmq
    - zoo
    - sqlite3

    depends_on:
    - rmq
    - zoo
    - sqlite3
    
    ports:
      - "80:80"
    restart: on-failure

  sqlite3:
    image: nouchka/sqlite3:latest
    ports: 
      - "27017:27017"

    
  